[package]
name = "galaxy"

version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true


[dependencies]
bevy.workspace = true
galaxy-core.workspace = true


[lints]
workspace = true
